generic-service:
  ingress:
    host: probation-search-api.hmpps.service.justice.gov.uk

  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    SENTRY_ENVIRONMENT: prod

  allowlist:
    groups:
      - delius-prod

generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
  openSearchAlertsDomainNames:
    cloud-platform-1cc47140: OpenSearch
  openSearchAlertsFreeStorageSpaceThresholdGB: 375
  openSearchAlertsClusterStatusYellowMinutes: 180