# Default config
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        timezone.default_storage: NORMALIZE
        query.mutation_strategy: org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
        query.mutation_strategy.persistent:
          create_tables: false
          drop_tables: false
        query.mutation_strategy.global_temporary:
          create_tables: false
          drop_tables: false
  threads.virtual.enabled: true

springdoc.default-produces-media-type: application/json

management:
  endpoints.web:
    base-path: /
    exposure.include: [ "health", "info" ]
  endpoint.health.show-details: always

info.productId: HMPPS518 # https://developer-portal.hmpps.service.justice.gov.uk/products/probation-integration-services-1

---
# Shared dev/test config
spring.config.activate.on-profile: dev
server.shutdown: immediate

spring:
  datasource.url: jdbc:tc:oracle:slim-faststart:///XEPDB1?TC_TMPFS=/testtmpfs:rw
  jpa.database: oracle
  jpa.hibernate.ddl-auto: create

logging.level:
  uk.gov.justice.digital.hmpps: DEBUG
