name: Build

on:
  push:
    branches-ignore:
      - main
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'on-failure'

      - name: Build
        run: ./gradlew check
