name: Deploy

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project
        type: choice
        required: true
        options:
          - api
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - dev
          - preprod
          - prod
      version:
        description: Image version (leave blank to build from branch)
        type: string
        required: false

permissions:
  contents: read
  checks: write
  packages: write

jobs:
  build:
    if: inputs.version == ''
    uses: ./.github/workflows/build.yml
    with:
      push: true
      force: true
      projects: '["${{ inputs.project }}"]'
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  deploy-build:
    if: inputs.version == ''
    uses: ./.github/workflows/pipeline-deploy.yml
    needs: build
    with:
      environment: ${{ inputs.environment }}
      project: ${{ inputs.project }}
      version: ${{needs.build.outputs.version }}
    secrets: inherit

  deploy-version:
    if: inputs.version != ''
    uses: ./.github/workflows/pipeline-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      project: ${{ inputs.project }}
      version: ${{ inputs.version}}
    secrets: inherit
